export const FACULTIES = [
  {
    name: "คณะอิสลามศึกษาและนิติศาสตร์",
    departments: [
      "สาขาวิชาอุศูลุดดีน (หลักสูตรนานาชาติ)",
      "สาขาวิชาอิสลามศึกษา",
      "สาขาวิชานิติศาสตร์",
      "สาขาวิชาชะรีอะฮฺ",
      "สาขาวิชาอัลกุรอานและอัสสุนนะฮฺ (หลักสูตรนานาชาติ)"
    ]
  },
  {
    name: "คณะศิลปศาสตร์และสังคมศาสตร์",
    departments: [
      "สาขาวิชาภาษาอาหรับ (หลักสูตรนานาชาติ)",
      "สาขาวิชารัฐประศาสนศาสตร์",
      "สาขาวิชาเศรษฐศาสตร์การเงินและการธนาคาร",
      "สาขาวิชาภาษาอังกฤษ (หลักสูตรนานาชาติ)",
      "สาขาวิชาภาษามลายู (หลักสูตรนานาชาติ)",
      "สาขาวิชาบริหารธุรกิจ"
    ]
  },
  {
    name: "คณะวิทยาศาสตร์และเทคโนโลยี",
    departments: [
      "สาขาวิชาเทคโนโลยีสารสนเทศ (หลักสูตรนานาชาติ)",
      "สาขาวิชาวิจัยและพัฒนาผลิตภัณฑ์อาหารฮาลาล",
      "สาขาวิชาวิทยาการข้อมูลและการวิเคราะห์ (หลักสูตรนานาชาติ)"
    ]
  },
  {
    name: "คณะศึกษาศาสตร์",
    departments: [
      "สาขาวิชาการศึกษาปฐมวัย",
      "สาขาวิชาอิสลามศึกษา",
      "สาขาวิชาภาษาอาหรับ",
      "สาขาวิชาวิทยาศาสตร์ทั่วไป",
      "สาขาวิชาภาษาอังกฤษ",
      "สาขาวิชาภาษามลายูและเทคโนโลยีการศึกษา"
    ]
  }
];

export const EMPLOYMENT_STATUS = [
  { id: "1", label: "ไม่มีงานทำก่อนการศึกษา มีงานทำหลังจบการศึกษา" },
  { id: "2", label: "ไม่มีงานทำก่อนการศึกษา มีงานทำหลังจบการศึกษาและกำลังศึกษาต่อ" },
  { id: "3", label: "ยังไม่มีงานทำ" },
  { id: "4", label: "ยังไม่มีงานทำ และกำลังศึกษาต่อ" },
  { id: "5", label: "มีงานทำก่อนจบการศึกษา อยู่ในสายงานเดิมหลังจบการศึกษา" },
  { id: "6", label: "มีงานทำก่อนจบการศึกษา เปลี่ยนสายงานหลังจบการศึกษา" },
  { id: "7", label: "มีงานทำก่อนจบการศึกษา อยู่ในสายงานเดิมหลังจบการศึกษา เลื่อนระดับ" }
];

export const MILITARY_STATUS = [
  { id: "0", label: "อยู่ในช่วงผ่อนผันเกณฑ์ทหาร หรือได้รับการยกเว้น หรือผ่านการเกณฑ์ทหารแล้ว" },
  { id: "1", label: "อยู่ในระหว่างการเป็นทหารเกณฑ์" }
];

export const JOB_TYPES = [
  { id: "01", label: "ข้าราชการ /เจ้าหน้าที่หน่วยงานของรัฐ" },
  { id: "02", label: "รัฐวิสาหกิจ" },
  { id: "03", label: "พนักงานบริษัท/องค์กรธุรกิจเอกชน" },
  { id: "04", label: "ดำเนินธุรกิจอิสระ/เจ้าของกิจการ" },
  { id: "05", label: "พนักงานองค์การต่างประเทศ/ระหว่างประเทศ" },
  { id: "00", label: "อื่นๆ (ระบุเพิ่มเติม)" }
];

export const SPECIAL_SKILLS = [
  { id: "01", label: "ด้านภาษาต่างประเทศ" },
  { id: "02", label: "ด้านการใช้คอมพิวเตอร์" },
  { id: "03", label: "ด้านกิจกรรมสันทนาการ" },
  { id: "04", label: "ด้านศิลปะ" },
  { id: "05", label: "ด้านกีฬา" },
  { id: "06", label: "ด้านนาฎศิลป/ดนตรีขับร้อง" },
  { id: "00", label: "อื่นๆ (ระบุเพิ่มเติม)" }
];

export const BUSINESS_TYPES = [
  { id: "A", label: "เกษตรกรรม การป่าไม้และการประมง" },
  { id: "B", label: "การทำเหมืองแร่และเหมืองหิน" },
  { id: "C", label: "การผลิต" },
  { id: "D", label: "ไฟฟ้า ก๊าซ ไอน้ำและระบบการปรับอากาศ" },
  { id: "E", label: "การจัดหาน้ำ การจัดการน้ำเสียและของเสีย รวมถึงกิจกรรมที่เกี่ยวข้อง" },
  { id: "F", label: "การก่อสร้าง" },
  { id: "G", label: "การขายส่งและการขายปลีกการซ่อมยานยนต์และจักรยานยนต์" },
  { id: "H", label: "การขนส่งและสถานที่เก็บสินค้า" },
  { id: "I", label: "ที่พักแรมและบริการด้านอาหาร" },
  { id: "J", label: "ข้อมูลข่าวสารและการสื่อสาร" },
  { id: "K", label: "กิจกรรมทางการเงินและการประกันภัย" },
  { id: "L", label: "กิจกรรมเกี่ยวกับอสังหาริมทรัพย์" },
  { id: "M", label: "กิจกรรมวิชาชีพ วิทยาศาสตร์ และกิจกรรมทางวิชาการ" },
  { id: "N", label: "กิจกรรมการบริหารและบริการสนับสนุนอื่น ๆ" },
  { id: "O", label: "การบริหารราชการ การป้องกันประเทศ และการประกันสังคมภาคบังคับ" },
  { id: "P", label: "การศึกษา" },
  { id: "Q", label: "กิจกรรมด้านสุขภาพและงานสังคมสงเคราะห์" },
  { id: "R", label: "ศิลปะ ความบันเทิงและนันทนาการ" },
  { id: "S", label: "กิจกรรมการบริการด้านอื่น ๆ" },
  { id: "T", label: "กิจกรรมการจ้างงานในครัวเรือน กิจกรรมการผลิตสินค้าและบริการที่ทำขึ้นเองเพื่อใช้ในครัวเรือน" },
  { id: "U", label: "กิจกรรมขององค์การระหว่างประเทศและภาคีสมาชิก" }
];

export const SATISFACTION = [
  { id: "01", label: "พอใจ" },
  { id: "02", label: "ระบบงานไม่ดี" },
  { id: "03", label: "ผู้ร่วมงานไม่ดี" },
  { id: "04", label: "ไม่ได้ใช้ความรู้ที่เรียนมา" },
  { id: "05", label: "ค่าตอบแทนต่ำ" },
  { id: "06", label: "ขาดความมั่นคง" },
  { id: "07", label: "ขาดความก้าวหน้า" },
  { id: "00", label: "อื่นๆ (ระบุเพิ่มเติม)" }
];

export const SEARCH_DURATION = [
  { id: "01", label: "ผู้ที่หางานได้ก่อนจบการศึกษา หรือได้งานทันทีหลังสำเร็จการศึกษา" },
  { id: "02", label: "1 – 2 เดือน" },
  { id: "03", label: "3 – 6 เดือน" },
  { id: "04", label: "7 - 9 เดือน" },
  { id: "05", label: "10 - 12 เดือน" },
  { id: "06", label: "มากกว่า 1 ปี" },
  { id: "07", label: "เป็นงานเดิมก่อนมาศึกษาหรือได้งานทำระหว่างศึกษา" }
];

export const UNEMPLOYED_REASONS = [
  { id: "1", label: "ยังไม่ประสงค์ทำงาน" },
  { id: "2", label: "รอฟังคำตอบจากหน่วยงาน" },
  { id: "3", label: "หางานทำไม่ได้" },
  { id: "4", label: "ต้องการประกอบอาชีพอิสระ" },
  { id: "0", label: "อื่นๆ (ระบุเพิ่มเติม)" }
];

export const JOB_SEARCH_PROBLEMS = [
  { id: "01", label: "ไม่มีปัญหา" },
  { id: "02", label: "ไม่ทราบแหล่งงาน" },
  { id: "03", label: "หางานที่ถูกใจไม่ได้" },
  { id: "04", label: "ต้องสอบจึงไม่อยากสมัคร" },
  { id: "05", label: "ขาดคนสนับสนุน" },
  { id: "06", label: "ขาดคนหรือเงินค้ำประกัน" },
  { id: "07", label: "หน่วยงานไม่ต้องการ" },
  { id: "08", label: "เงินเดือนน้อย" },
  { id: "09", label: "สอบเข้าทำงานไม่ได้" },
  { id: "10", label: "ปัญหาด้านสุขภาพ" },
  { id: "11", label: "ขาดทักษะภาษาต่างประเทศ" },
  { id: "12", label: "ขาดทักษะด้านคอมพิวเตอร์" },
  { id: "13", label: "ขาดประสบการณ์ในการทำงาน" },
  { id: "14", label: "เกรดเฉลี่ยไม่ถึงเกณฑ์ที่กำหนด" },
  { id: "00", label: "อื่นๆ (ระบุเพิ่มเติม)" }
];

export const DATA_DISCLOSURE = [
  { id: "0", label: "ไม่ยินยอมเปิดเผยข้อมูล" },
  { id: "1", label: "ยินยอมเปิดเผยข้อมูลต่อนายจ้างทุกประเภท" },
  { id: "2", label: "ยินยอมเปิดเผยข้อมูลยกเว้นนายจ้างประเภทจ้างเหมาแรงงาน" },
  { id: "3", label: "ยินยอมเปิดเผยข้อมูลยกเว้นนายจ้างประเภทขายประกัน/ขายตรง" },
  { id: "4", label: "ยินยอมเปิดเผยข้อมูลยกเว้นนายจ้างประเภทจ้างเหมาแรงงาน และประเภทขายประกัน/ขายตรง" }
];

export const EDU_LEVELS = [
  { id: "35", label: "อนุปริญญา" },
  { id: "40", label: "ปริญญาตรี" },
  { id: "50", label: "ประกาศนียบัตรบัณฑิต" },
  { id: "60", label: "ปริญญาโท" },
  { id: "70", label: "ประกาศนียบัตรบัณฑิตชั้นสูง" },
  { id: "80", label: "ปริญญาเอก" },
  { id: "90", label: "ประกาศนียบัตรหรือหลักสูตรเฉพาะ" }
];

export const STUDY_REASONS = [
  { id: "1", label: "เป็นความต้องการของบิดา/มารดา หรือผู้ปกครอง" },
  { id: "2", label: "งานที่ต้องการต้องใช้วุฒิสูงกว่า ปริญญาตรี" },
  { id: "3", label: "ได้รับทุนศึกษาต่อ" },
  { id: "4", label: "เป็นความต้องการของตนเอง" },
  { id: "0", label: "อื่นๆ (ระบุเพิ่มเติม)" }
];

export const STUDY_PROBLEMS = [
  { id: "01", label: "ไม่มีปัญหา" },
  { id: "02", label: "ข้อมูลสถานที่ศึกษาต่อไม่เพียงพอ" },
  { id: "03", label: "คุณสมบัติในการสมัครเรียน" },
  { id: "04", label: "ขาดความรู้พื้นฐานในการศึกษาต่อ" },
  { id: "05", label: "ขาดแคลนเงินทุน" },
  { id: "00", label: "อื่นๆ (ระบุเพิ่มเติม)" }
];

export const COUNTRIES = [
  { id: "TH", label: "THAILAND" },
  { id: "AD", label: "ANDORRA" },
  { id: "AE", label: "UNITED ARAB EMIRATES" },
  { id: "AF", label: "AFGHANISTAN" },
  { id: "AG", label: "ANTIGUA AND BARBUDA" },
  { id: "AI", label: "ANGUILLA" },
  { id: "AL", label: "ALBANIA" },
  { id: "AM", label: "ARMENIA" },
  { id: "AN", label: "NETHERLANDS ANTILLES" },
  { id: "AO", label: "ANGOLA" },
  { id: "AQ", label: "ANTARCTICA" },
  { id: "AR", label: "ARGENTINA" },
  { id: "AS", label: "AMERICAN SAMOA" },
  { id: "AT", label: "AUSTRIA" },
  { id: "AU", label: "AUSTRALIA" },
  { id: "AW", label: "ARUBA" },
  { id: "AX", label: "LAND ISLANDS" },
  { id: "AZ", label: "AZERBAIJAN" },
  { id: "BA", label: "BOSNIA AND HERZEGOVINA" },
  { id: "BB", label: "BARBADOS" },
  { id: "BD", label: "BANGLADESH" },
  { id: "BE", label: "BELGIUM" },
  { id: "BF", label: "BURKINA FASO" },
  { id: "BG", label: "BULGARIA" },
  { id: "BH", label: "BAHRAIN" },
  { id: "BI", label: "BURUNDI" },
  { id: "BJ", label: "BENIN" },
  { id: "BM", label: "BERMUDA" },
  { id: "BN", label: "BRUNEI DARUSSALAM" },
  { id: "BO", label: "BOLIVIA" },
  { id: "BR", label: "BRAZIL" },
  { id: "BS", label: "BAHAMAS" },
  { id: "BT", label: "BHUTAN" },
  { id: "BV", label: "BOUVET ISLAND" },
  { id: "BW", label: "BOTSWANA" },
  { id: "BY", label: "BELARUS" },
  { id: "BZ", label: "BELIZE" },
  { id: "CA", label: "CANADA" },
  { id: "CC", label: "COCOS (KEELING) ISLANDS" },
  { id: "CD", label: "CONGO, THE DEMOCRATIC REPUBLIC OF THE" },
  { id: "CF", label: "CENTRAL AFRICAN REPUBLIC" },
  { id: "CG", label: "CONGO" },
  { id: "CH", label: "SWITZERLAND" },
  { id: "CI", label: "CÔTE D'IVOIRE" },
  { id: "CK", label: "COOK ISLANDS" },
  { id: "CL", label: "CHILE" },
  { id: "CM", label: "CAMEROON" },
  { id: "CN", label: "CHINA" },
  { id: "CO", label: "COLOMBIA" },
  { id: "CR", label: "COSTA RICA" },
  { id: "CS", label: "SERBIA AND MONTENEGRO" },
  { id: "CU", label: "CUBA" },
  { id: "CV", label: "CAPE VERDE" },
  { id: "CX", label: "CHRISTMAS ISLAND" },
  { id: "CY", label: "CYPRUS" },
  { id: "CZ", label: "CZECH REPUBLIC" },
  { id: "DE", label: "GERMANY" },
  { id: "DJ", label: "DJIBOUTI" },
  { id: "DK", label: "DENMARK" },
  { id: "DM", label: "DOMINICA" },
  { id: "DO", label: "DOMINICAN REPUBLIC" },
  { id: "DZ", label: "ALGERIA" },
  { id: "EC", label: "ECUADOR" },
  { id: "EE", label: "ESTONIA" },
  { id: "EG", label: "EGYPT" },
  { id: "EH", label: "WESTERN SAHARA" },
  { id: "ER", label: "ERITREA" },
  { id: "ES", label: "SPAIN" },
  { id: "ET", label: "ETHIOPIA" },
  { id: "FI", label: "FINLAND" },
  { id: "FJ", label: "FIJI" },
  { id: "FK", label: "FALKLAND ISLANDS (MALVINAS)" },
  { id: "FM", label: "MICRONESIA, FEDERATED STATES OF" },
  { id: "FO", label: "FAROE ISLANDS" },
  { id: "FR", label: "FRANCE" },
  { id: "GA", label: "GABON" },
  { id: "GB", label: "UNITED KINGDOM" },
  { id: "GD", label: "GRENADA" },
  { id: "GE", label: "GEORGIA" },
  { id: "GF", label: "FRENCH GUIANA" },
  { id: "GH", label: "GHANA" },
  { id: "GI", label: "GIBRALTAR" },
  { id: "GL", label: "GREENLAND" },
  { id: "GM", label: "GAMBIA" },
  { id: "GN", label: "GUINEA" },
  { id: "GP", label: "GUADELOUPE" },
  { id: "GQ", label: "EQUATORIAL GUINEA" },
  { id: "GR", label: "GREECE" },
  { id: "GS", label: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS" },
  { id: "GT", label: "GUATEMALA" },
  { id: "GU", label: "GUAM" },
  { id: "GW", label: "GUINEA-BISSAU" },
  { id: "GY", label: "GUYANA" },
  { id: "HK", label: "HONG KONG" },
  { id: "HM", label: "HEARD ISLAND AND MCDONALD ISLANDS" },
  { id: "HN", label: "HONDURAS" },
  { id: "HR", label: "CROATIA" },
  { id: "HT", label: "HAITI" },
  { id: "HU", label: "HUNGARY" },
  { id: "ID", label: "INDONESIA" },
  { id: "IE", label: "IRELAND" },
  { id: "IL", label: "ISRAEL" },
  { id: "IN", label: "INDIA" },
  { id: "IO", label: "BRITISH INDIAN OCEAN TERRITORY" },
  { id: "IQ", label: "IRAQ" },
  { id: "IR", label: "IRAN, ISLAMIC REPUBLIC OF" },
  { id: "IS", label: "ICELAND" },
  { id: "IT", label: "ITALY" },
  { id: "JM", label: "JAMAICA" },
  { id: "JO", label: "JORDAN" },
  { id: "JP", label: "JAPAN" },
  { id: "KE", label: "KENYA" },
  { id: "KG", label: "KYRGYZSTAN" },
  { id: "KH", label: "CAMBODIA" },
  { id: "KI", label: "KIRIBATI" },
  { id: "KM", label: "COMOROS" },
  { id: "KN", label: "SAINT KITTS AND NEVIS" },
  { id: "KP", label: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF" },
  { id: "KR", label: "KOREA, REPUBLIC OF" },
  { id: "KW", label: "KUWAIT" },
  { id: "KY", label: "CAYMAN ISLANDS" },
  { id: "KZ", label: "KAZAKHSTAN" },
  { id: "LA", label: "LAO PEOPLE'S DEMOCRATIC REPUBLIC" },
  { id: "LB", label: "LEBANON" },
  { id: "LC", label: "SAINT LUCIA" },
  { id: "LI", label: "LIECHTENSTEIN" },
  { id: "LK", label: "SRI LANKA" },
  { id: "LR", label: "LIBERIA" },
  { id: "LS", label: "LESOTHO" },
  { id: "LT", label: "LITHUANIA" },
  { id: "LU", label: "LUXEMBOURG" },
  { id: "LV", label: "LATVIA" },
  { id: "LY", label: "LIBYAN ARAB JAMAHIRIYA" },
  { id: "MA", label: "MOROCCO" },
  { id: "MC", label: "MONACO" },
  { id: "MD", label: "MOLDOVA, REPUBLIC OF" },
  { id: "MG", label: "MADAGASCAR" },
  { id: "MH", label: "MARSHALL ISLANDS" },
  { id: "MK", label: "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF" },
  { id: "ML", label: "MALI" },
  { id: "MM", label: "MYANMAR" },
  { id: "MN", label: "MONGOLIA" },
  { id: "MO", label: "MACAO" },
  { id: "MP", label: "NORTHERN MARIANA ISLANDS" },
  { id: "MQ", label: "MARTINIQUE" },
  { id: "MR", label: "MAURITANIA" },
  { id: "MS", label: "MONTSERRAT" },
  { id: "MT", label: "MALTA" },
  { id: "MU", label: "MAURITIUS" },
  { id: "MV", label: "MALDIVES" },
  { id: "MW", label: "MALAWI" },
  { id: "MX", label: "MEXICO" },
  { id: "MY", label: "MALAYSIA" },
  { id: "MZ", label: "MOZAMBIQUE" },
  { id: "NA", label: "NAMIBIA" },
  { id: "NC", label: "NEW CALEDONIA" },
  { id: "NE", label: "NIGER" },
  { id: "NF", label: "NORFOLK ISLAND" },
  { id: "NG", label: "NIGERIA" },
  { id: "NI", label: "NICARAGUA" },
  { id: "NL", label: "NETHERLANDS" },
  { id: "NO", label: "NORWAY" },
  { id: "NP", label: "NEPAL" },
  { id: "NR", label: "NAURU" },
  { id: "NU", label: "NIUE" },
  { id: "NZ", label: "NEW ZEALAND" },
  { id: "OM", label: "OMAN" },
  { id: "PA", label: "PANAMA" },
  { id: "PE", label: "PERU" },
  { id: "PF", label: "FRENCH POLYNESIA" },
  { id: "PG", label: "PAPUA NEW GUINEA" },
  { id: "PH", label: "PHILIPPINES" },
  { id: "PK", label: "PAKISTAN" },
  { id: "PL", label: "POLAND" },
  { id: "PM", label: "SAINT PIERRE AND MIQUELON" },
  { id: "PN", label: "PITCAIRN" },
  { id: "PR", label: "PUERTO RICO" },
  { id: "PS", label: "PALESTINIAN TERRITORY, OCCUPIED" },
  { id: "PT", label: "PORTUGAL" },
  { id: "PW", label: "PALAU" },
  { id: "PY", label: "PARAGUAY" },
  { id: "QA", label: "QATAR" },
  { id: "RE", label: "RÉUNION" },
  { id: "RO", label: "ROMANIA" },
  { id: "RU", label: "RUSSIAN FEDERATION" },
  { id: "RW", label: "RWANDA" },
  { id: "SA", label: "SAUDI ARABIA" },
  { id: "SB", label: "SOLOMON ISLANDS" },
  { id: "SC", label: "SEYCHELLES" },
  { id: "SD", label: "SUDAN" },
  { id: "SE", label: "SWEDEN" },
  { id: "SG", label: "SINGAPORE" },
  { id: "SH", label: "SAINT HELENA" },
  { id: "SI", label: "SLOVENIA" },
  { id: "SJ", label: "SVALBARD AND JAN MAYEN" },
  { id: "SK", label: "SLOVAKIA" },
  { id: "SL", label: "SIERRA LEONE" },
  { id: "SM", label: "SAN MARINO" },
  { id: "SN", label: "SENEGAL" },
  { id: "SO", label: "SOMALIA" },
  { id: "SR", label: "SURINAME" },
  { id: "ST", label: "SAO TOME AND PRINCIPE" },
  { id: "SV", label: "EL SALVADOR" },
  { id: "SY", label: "SYRIAN ARAB REPUBLIC" },
  { id: "SZ", label: "SWAZILAND" },
  { id: "TC", label: "TURKS AND CAICOS ISLANDS" },
  { id: "TD", label: "CHAD" },
  { id: "TF", label: "FRENCH SOUTHERN TERRITORIES" },
  { id: "TG", label: "TOGO" },
  { id: "TH", label: "THAILAND" },
  { id: "TJ", label: "TAJIKISTAN" },
  { id: "TK", label: "TOKELAU" },
  { id: "TL", label: "TIMOR-LESTE" },
  { id: "TM", label: "TURKMENISTAN" },
  { id: "TN", label: "TUNISIA" },
  { id: "TO", label: "TONGA" },
  { id: "TR", label: "TURKEY" },
  { id: "TT", label: "TRINIDAD AND TOBAGO" },
  { id: "TV", label: "TUVALU" },
  { id: "TW", label: "TAIWAN, PROVINCE OF CHINA" },
  { id: "TZ", label: "TANZANIA, UNITED REPUBLIC OF" },
  { id: "UA", label: "UKRAINE" },
  { id: "UG", label: "UGANDA" },
  { id: "UM", label: "UNITED STATES MINOR OUTLYING ISLANDS" },
  { id: "US", label: "UNITED STATES" },
  { id: "UY", label: "URUGUAY" },
  { id: "UZ", label: "UZBEKISTAN" },
  { id: "VA", label: "Vatican City State" },
  { id: "VC", label: "SAINT VINCENT AND THE GRENADINES" },
  { id: "VE", label: "VENEZUELA" },
  { id: "VG", label: "VIRGIN ISLANDS, BRITISH" },
  { id: "VI", label: "VIRGIN ISLANDS, U.S." },
  { id: "VN", label: "VIET NAM" },
  { id: "VU", label: "VANUATU" },
  { id: "WF", label: "WALLIS AND FUTUNA" },
  { id: "WS", label: "SAMOA" },
  { id: "YE", label: "YEMEN" },
  { id: "YT", label: "MAYOTTE" },
  { id: "ZA", label: "SOUTH AFRICA" },
  { id: "ZM", label: "ZAMBIA" },
  { id: "ZW", label: "ZIMBABWE" }
];
